pcc_gui/feature2/urls.py
from django.conf.urls import url

from . import views

app_name = 'feature2'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^loadfmm', views.loadfmm, name='loadfmm'),
    url(r'^group2', views.dependency_view2, name='group2'),
    url(r'^showdetails', views.showdetails, name='showdetails'),
]

pcc_gui/pcc_gui/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^features/', include('features.urls')),
    url(r'^feature2/', include('feature2.urls')),
    url(r'^admin/', admin.site.urls),
]

pcc_gui/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

pcc_gui/feature2/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Group(models.Model):
    name = models.CharField(max_length=100, blank=True)     # FMM page

    def __str__(self):
        return self.name


class Function(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, blank=True)          # FMM major function group

    def __str__(self):
        return self.name


class Feature(models.Model):
    CHOICE = 'CHO'
    SELECTION = 'SEL'

    RULE_TYPES = (
        (CHOICE, 'choice'),
        (SELECTION, 'selection'),
    )

    function = models.ForeignKey(Function, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, blank=True)                              # FMM feature name
    selection_name = models.CharField(max_length=100, blank=True)                   # FMM keyword selection
    rule_type = models.CharField(max_length=15, blank=True, choices=RULE_TYPES)     # FMM rule for selection
    option_min = models.IntegerField(blank=True, null=True)                         # FMM range of options minimum
    option_max = models.IntegerField(blank=True, null=True)                         # FMM range of options maximum
    enabled = models.NullBooleanField(default=False)                                # Feature enabled state
    selected = models.NullBooleanField(default=False)                               # Feature selected state

    def __str__(self):
        return self.name


class Dependency(models.Model):
    feature = models.ForeignKey(Feature, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, blank=True)          # FMM required dependency

    def __str__(self):
        return self.name

pcc_gui/feature2/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView
from django.template import loader

from .models import Group, Function, Feature, Dependency

# Create your views here.
def index(request):
    return HttpResponse("Hello, world. You're at the feature2 index.")

def loadfmm(request):
    fmm = open('FMM.txt', 'r')
    line_count = 0
    Group.objects.all().delete() # Scrub the database before processing FMM.txt

    for line in fmm:
        line_data = line.rstrip().split(',')

        group_name = line_data[0]
        function_name = line_data[1]
        feature_name = line_data[2]
        selection_name = line_data[3]
        dependencies = line_data[4].split(";")
        choice_type = line_data[5]
        option_min = line_data[6]
        option_max = line_data[7]

        groups = Group.objects.filter(name=group_name)  # Add Group if it does not exist
        if groups.count() == 0:
            group = Group(name=group_name)
            group.save()
        group = Group.objects.get(name=group_name)

        functions = Function.objects.filter(name=function_name)  # Add Function if it does not exist
        if functions.count() == 0:
            function = group.function_set.create(name=function_name)
            function.save()
        function = Function.objects.get(name=function_name)

        features = Feature.objects.filter(name=feature_name)  # Add Feature if it does not exist
        if features.count() == 0:
            feature = function.feature_set.create(name=feature_name)
            feature.selection_name=selection_name
            feature.choice_type=choice_type
            feature.option_min=option_min
            feature.option_max=option_max
            feature.save()
        feature = Feature.objects.get(name=feature_name)

        for dependency in dependencies:
            if dependency != "n/a":
                feature.dependency_set.create(name=dependency)
        feature.save()

        line_count += 1

    response_text = "FMM.txt load complete. " + str(line_count) + " records Processed. "
    return HttpResponse(response_text)


def dependency_view2(request):
    template = loader.get_template('feature2/dependency_list.html')

    dependency_list = Dependency.objects.select_related()

    context = {
        'dependency_list': dependency_list,
    }
    return HttpResponse(template.render(context, request))


def showdetails(request):
    template = loader.get_template('feature2/showdetails.html')

    print 'rev 6'
    objects = Function.objects.select_related()

    for object in objects:
        fields = dict((field.name, field.value_to_string(object)) for field in object._meta.fields)

    print fields

    return HttpResponse(template.render(fields, request))

pcc_gui/feature2/templates/feature2/dependency_list.html
<h2>Dependency List 1</h2>
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% if dependency_list %}
    <table class="table table-striped table-condensed">
        <caption>Dependency List</caption>
        <thead>
            <tr>
                <th>  Feature Group </th>
                <th>  Major Function </th>
                <th>  Feature </th>
                <th>  Dependency </th>
            </tr>
        </thead>

        <tbody>
        {% for dependency in dependency_list %}
                <tr>
                    <td>  {{ dependency.feature.function.group.name }} </td>
                    <td>  {{ dependency.feature.function.name }} </td>
                    <td>  {{ dependency.feature.name }} </td>
                    <td>  {{ dependency.name }} </td>
                </tr>
        </tbody>
        {% endfor %}
    </table>

{% else %}
    <p>There are no dependencies in the database.</p>
{% endif %}

pcc_gui/feature2/templates/feature2/group_list.html
<h2>Dependency List 1</h2>

{% if dependency_list %}
    {% for function in function_list %}
    <table>
        <tr>
            <td>  {{ dependency.feature.function.group.name }} </td> |
            <td>  {{ dependency.feature.function.name }} </td> |
            <td>  {{ dependency.feature.name }} </td> |
            <td>  {{ dependency.name }} </td>
        </tr>
    </table>
    {% endfor %}
{% else %}
    <p>There are no dependencies in the database.</p>
{% endif %}

pcc_gui/feature2/templates/feature2/showdetails.html
<h2> Show Details rev 5 </h2>

{% for object in objects %}
    <tr>
    {% for field, value in object.fields.iteritems %}
        <td>{{ field }} : {{ value }}</td>
    {% endfor %}
    </tr>
{% endfor %}